-- Migration 002: Create characters table
CREATE TABLE IF NOT EXISTS characters (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(512) DEFAULT NULL,
    gender VARCHAR(50) DEFAULT NULL,
    personality TEXT NOT NULL,
    tone VARCHAR(100) NOT NULL,
    humor TINYINT UNSIGNED NOT NULL DEFAULT 5,
    friendliness TINYINT UNSIGNED NOT NULL DEFAULT 5,
    creativity TINYINT UNSIGNED NOT NULL DEFAULT 5,
    style VARCHAR(100) NOT NULL,
    backstory TEXT DEFAULT NULL,
    interests JSON DEFAULT NULL,
    greeting TEXT NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_characters_user_id (user_id),
    CONSTRAINT fk_characters_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
